CREATE TABLE MEMBER(
	idx INT AUTO_INCREMENT PRIMARY key,
	id VARCHAR(20) NOT NULL UNIQUE,
	pw VARCHAR(50) NOT NULL,
	name VARCHAR(50) NOT NULL,
	email VARCHAR(50) NOT NULL,
	regdate date
);

CREATE TABLE board(
	idx INT AUTO_INCREMENT PRIMARY key,
	writer VARCHAR(20) NOT NULL UNIQUE,
	title VARCHAR(50) NOT NULL,
	content VARCHAR(2000) NOT NULL,
	regdate date
);